widgets:
  -
    id: active_users_weekly
    title: 'Active users'
    subtitle: 'Weekly'
    type: 'line'
    group: 'logging_api'
    style: wide
  -
    id: active_users_monthly
    title: 'Active users'
    subtitle: 'Monthly'
    type: 'line'
    group: 'logging_api'
    style: wide
